[tool]
[tool.poetry]
authors = ["prakashsellathurai@gmail.com"]
name = "type-without-typo"
version = "0.0.0"
description="Toy typo corrector with 80-90 % accuracy"
[tool.poetry.dependencies]
flask = "==1.0.2"
python = "^3.8"
